# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 565d88673fb8162d0f29506e0e64fdbdd22af2dff1a83f329fcf5fd43628862bf4c3327a3699a5694ba82b95ba9e627ea8cfc6d1e2d74ebec181cdd08af02f88

test:
  secret_key_base: 31e1db2388a4a9b8d80beeb9da84233f31802ad5c3cc8b789c79d5ddf6b4a3a60c3b44294400792c6b06c9665ec7e91c9a89e20fd3bd7b3aa1be7456628b6121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
